---
title: Use Case 010 - Domain Model
---
classDiagram
    direction TB

    class Dashboard {
        NatureCheck
        KPI
        Graphs
        Assignments
    }

    class DataOverview {
        displayNatureCheck
        displayKPI
        displayGraphs
        displayAssigments
    }

    class Role {
        roleName
    }

    note for Dashboard "Represents the dashboard interface for users to view summaries and key metrics."
    note for DataOverview "Provides detailed views and filtering options for datasets."
    note for Role "Represents a user of the system with authentication capabilities."
    Dashboard "1" -- "*" DataOverview
    Role "1" -- "1" Dashboard
